import { StatusCodes } from "http-status-codes";

export const HTTP_STATUS = {
   OK: StatusCodes.OK, // 200
   CREATED: StatusCodes.CREATED, // 201
   ACCEPTED: StatusCodes.ACCEPTED, // 202
   NO_CONTENT: StatusCodes.NO_CONTENT, // 204
   BAD_REQUEST: StatusCodes.BAD_REQUEST, // 400
   UNAUTHORIZED: StatusCodes.UNAUTHORIZED, // 401
   FORBIDDEN: StatusCodes.FORBIDDEN, // 403
   NOT_FOUND: StatusCodes.NOT_FOUND, // 404
   METHOD_NOT_ALLOWED: StatusCodes.METHOD_NOT_ALLOWED, // 405
   CONFLICT: StatusCodes.CONFLICT, // 409
   UNPROCESSABLE_ENTITY: StatusCodes.UNPROCESSABLE_ENTITY, // 422
   TOO_MANY_REQUESTS: StatusCodes.TOO_MANY_REQUESTS, // 429
   INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR, // 500
   NOT_IMPLEMENTED: StatusCodes.NOT_IMPLEMENTED, // 501
   BAD_GATEWAY: StatusCodes.BAD_GATEWAY, // 502
   SERVICE_UNAVAILABLE: StatusCodes.SERVICE_UNAVAILABLE, // 503
   GATEWAY_TIMEOUT: StatusCodes.GATEWAY_TIMEOUT // 504
};
